server:
  port: 8888

spring:
  application:
    name: config-service  cloud:    config:      server:        native:          search-locations:          - classpath:config
  profiles:    active:    - native
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
  